---
title: "End Of Meeting Notes For Charta Digitalisierung"
output: html_notebook
---

<!-- ----------------------------------------------- --
  -- TODO: * Mention decision of Merkel wrt Huawei   --
  --                                                 --
  -- ----------------------------------------------- -->
  
## Addendum To Discussion
Ein paar Zuhörende waren daran interessiert, weshalb Sunrise mit Huawei zusammenarbeitet. Der Grund für diese Frage liegt in der unklaren Stellung von Huawei zum offiziellen China. Bis zu diesem Zeitpunkt hatte ich selber geglaubt, dass Huawei praktisch der einzige Anbieter von 5G-Routern ist. Eine Kontroverse um den Entscheid der Deutschen Bundeskanzlerin Angela Merkel, Huawei als Anbieter nicht auszuschliessen, hat aber gezeigt, dass Sony-Eriksson auch als möglicher Anbieter in Frage käme. Ob für Sunrise oder für die deutsche Regierung von den Chinesen ein paar Belohnungen entlang der entstehenden Seidenstrasse platziert sind, bleibt uns allen bis zum aktuellen Zeitpunkt verborgen.  
  

## Blockchain
Als Abschluss der Tagung hat Fabian Wahl über den Blockchain Hackathon berichtet. Die Leute, welche bis zum Schluss der Tagung geblieben sind, wurden mit einem sehr spannenden Beitrag belohnt. Mit grossem Engagement und einer guten Portion an Motivation wurde das Publikum in die komplexe Materie der Blockchain-Technologie eingeführt. Als zweiter Schwerpunkt enthielt der Vortrag von Fabian Wahl den Hackathon zum Thema Blockchain. Sein Team hat im Bereich Einsatz von Blockchain im FoodAgri Bereich gleich mehrere Preise gewonnen. 


## Zusammenfassung
Die Jahrestagung gab eine guten Überblick über wo die einzelnen Organisationen im Bezug auf Vernetzung der Daten stehen. Aktuell werden in allen Organisationen sehr grosse Anstrengungen unternommen die internen Daten zu vernetzen damit ein optimaler Nutzen aus den gesammelten Daten gewonnen werden kann. Eine stärkere Integration von Daten zwischen Organisationen, welche eine transparente Nutzung aller Daten über Organisationen hinweg möglich machen würde, ist ein für die Landwirtschaft wichtiges Zukunftsprojekt. Dieses wartet aber noch nicht an der nächsten Ecke und es bleibt noch viel Arbeit zu tun bis ein solches Datenintegrationsprojekt realisiert werden kann. Die Charta Digitalisierung ist eine spannende Plattform für solche Projekte. Es bleibt also spannend und deshalb gilt es sicher dabei zu bleiben und die zukünftigen Entwicklungen aufmerksam zu verfolgen.   
